# Generated by Django 4.2.15 on 2024-08-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('List_API', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
